# Site Settings
title: Abecedarul carierei | OSUT
email: youremail@xyz.com
description: Blogul ABC Cariera
baseurl: "/jekflix-template" # the subpath of your site, e.g. /blog
url: "https://abc.osut.ro" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: ABCdarul Carierei
user_description: Abecedarul Carierei
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: abcdarul.carierei
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
